// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace rawg_api.Models;

[Table("games")]
public partial class Game
{
    [Key]
    [Column("id_games")]
    public int IdGames { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("metacritic")]
    public int? Metacritic { get; set; }

    [Column("background_image")]
    [StringLength(255)]
    public string BackgroundImage { get; set; }

    [ForeignKey("GamesIdGames")]
    [InverseProperty("GamesIdGames")]
    public virtual ICollection<Genre> GenresIdGenres { get; set; } = new List<Genre>();

    [ForeignKey("GamesIdGames")]
    [InverseProperty("GamesIdGames")]
    public virtual ICollection<ParentPlatform> ParentPlatformsIdParentPlatforms { get; set; } = new List<ParentPlatform>();

    [ForeignKey("GamesIdGames")]
    [InverseProperty("GamesIdGames")]
    public virtual ICollection<Store> StoresIdStores { get; set; } = new List<Store>();
}