// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace rawg_api.Models;

[Table("genres")]
public partial class Genre
{
    [Key]
    [Column("id_genres")]
    public int IdGenres { get; set; }

    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; } = null!;

    [Column("image_background")]
    [StringLength(255)]
    public string? ImageBackground { get; set; }

    [ForeignKey("GenresIdGenres")]
    [InverseProperty("GenresIdGenres")]
    public virtual ICollection<Game> GamesIdGames { get; set; } = new List<Game>();
}