// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace rawg_api.Models;

[Table("parent_platforms")]
public partial class ParentPlatform
{
    [Key]
    [Column("id_parent_platforms")]
    public int IdParentPlatforms { get; set; }

    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; } = null!;

    [Column("slug")]
    [StringLength(255)]
    public string Slug { get; set; } = null!;

    [ForeignKey("ParentPlatformsIdParentPlatforms")]
    [InverseProperty("ParentPlatformsIdParentPlatforms")]
    public virtual ICollection<Game> GamesIdGames { get; set; } = new List<Game>();
}