services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_RAWG_API_KEY=${VITE_RAWG_API_KEY}
      - VITE_API_URL=${VITE_API_URL}
